services:
  postgres:
    image: postgres:latest
    container_name: job-scheduler-postgres
    environment:
      POSTGRES_DB: job_scheduler
      POSTGRES_USER: job_scheduler
      POSTGRES_PASSWORD: job_scheduler
    ports:
      - "5445:5432"
    volumes:
      - pg-sch-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: job-scheduler-redis
    command: ["redis-server", "--save", "60", "1000", "--loglevel", "warning"]
    ports:
      - "6379:6379"

volumes:
  pg-sch-data:
