version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: job-scheduler-postgres
    environment:
      POSTGRES_DB: job_scheduler
      POSTGRES_USER: job_scheduler
      POSTGRES_PASSWORD: job_scheduler
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: job-scheduler-redis
    command: ["redis-server", "--save", "60", "1000", "--loglevel", "warning"]
    ports:
      - "6379:6379"

  app:
    container_name: job-scheduler-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: job_scheduler
      DB_USERNAME: job_scheduler
      DB_PASSWORD: job_scheduler
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    restart: unless-stopped