[versions]
spring-boot = "4.0.0"
lombok = "1.18.42"
shedlock = "7.2.1"
logstash-logback-encoder = "9.0"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

spring-boot-starter-webmvc   = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-test     = { module = "org.springframework.boot:spring-boot-starter-test" }

shedlock-spring       = { module = "net.javacrumbs.shedlock:shedlock-spring", version.ref = "shedlock" }
shedlock-redis-spring = { module = "net.javacrumbs.shedlock:shedlock-provider-redis-spring", version.ref = "shedlock" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
