apiVersion: v1
kind: Service
metadata:
  name: job-scheduler-service
  labels:
    app: job-scheduler-service
spec:
  type: LoadBalancer
  selector:
    app: job-scheduler-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
